### ISSUE TITLE
Buoy light is backwards with shaders

### ISSUE THREAD

**Issue by mxKeaton** [hybridlabs/hybrid-aquatic#16]
I am running Complementary Shaders and I assume that you tried to inregrate some shaders functionality to the buoy to light them up in the night and turn them off during the day. Great idea, but I think it is implemented backwards, because it turns off during the night and lights up during the day.

![image](https://github.com/hybridlabs/hybrid-aquatic/assets/83590708/a6c8a4b6-1eb0-4643-a182-e66ae6f527c0)
![image](https://github.com/hybridlabs/hybrid-aquatic/assets/83590708/144b3c82-ec0a-4ad6-86b3-befab66715a7)

Playing on the new HA update

**Comment by MysticKoko** [comment]
We actually have not implemented that at all, theyre meant to stay lit all the time, and this is probably just a shader bug. I dont think we can fix it in our end because we did the buoys the same way we did every other glowing texture in the mod and so it should work fine

**Comment by mxKeaton** [comment]
That's odd :/

Every glowing fish texture works without any issues. I guess I will have to Ignore it then.

**Comment by MysticKoko** [comment]
Im going to close this issue for now but if we ever find a fix for it on our end (unlikely so no promises) I'll reopen it and let you know it's fixed

**Comment by DmitriBogdanov** [comment]
It seems Iris doesn't know how handle light interaction with the glowmask, you can fix it by making a resourcepack that replaces `assets/hybrid-aquatic/textures/block/buoy_glowmask.png` with an "empty" one:

**New texture:**
![buoy_glowmask_texture](https://github.com/user-attachments/assets/d2392e3d-23fb-4978-88c9-64c272f09f17)
(glowmask contains 4 pixels that are hidden under the lamp post, it's necessary since making a whole glowmask empty causes a crash)

**Screenshot with Bliss shader:**
![screenshot_with_bliss_shader](https://github.com/user-attachments/assets/885ac074-9a32-42da-bf14-5c011f7123a2)
