### ISSUE TITLE
Vanilla torch loot table override.

### ISSUE THREAD

**Issue by AlienXtream** [hybridlabs/hybrid-aquatic#18]
live version has a loot table override for vanilla torches. unsure if intentional or a remenant of testing something. 

if this represents an intentional change, i suggest this be removed pending better design changes to vanilla mechanics that are clearly indicated via gameplay (e.g dropping "extinguished torch"). otherwise, it just appears to be a bug and can be a real headache to find. 

https://github.com/hybridlabs/hybrid-aquatic/blame/1.20_Crabs/src/generated/resources/data/minecraft/loot_tables/blocks/torch.json

**Comment by MysticKoko** [comment]
Thanks for the report, I just woke up and will look into it right away

**Comment by MysticKoko** [comment]
Fixed in the 1.3.2 update - should be uploaded sometime today/tomorrow on Curseforge and Modrinth

**Comment by AlienXtream** [comment]
i i may ask, what was the reason for the loot table override in the first place? unintentional leftover from testing or something to do with future features?

**Comment by MysticKoko** [comment]
It was a bug to do with the wall glowstick block, you didnt notice it but its also present with the wall coral fans we added. Apparently trying to register a loot table for the "wall" variant of any block that copies a vanilla blocks settings (such as coral fans and torches) will override the loot table for the original block instead of the modded one

The 1.3.2 patch is out on Modrinth btw, it fixes this bug and a few others. Still awaiting Curseforge approval though

**Comment by AlienXtream** [comment]
well... how nice of it... love when computers do things you dont want and dont tell you... XD
