### ISSUE TITLE
Bugs and critters <3

### ISSUE THREAD

**Issue by BioTechproject27** [hybridlabs/hybrid-aquatic#4]
First off I wanna say: absolutely beautiful concept, I love it and what's already in the game!
Secondly, I realize that this is still a new mod, so obviously there'll be a lot of bugs, but maybe this will help draw some attention to some of them. And most are probably being worked on already.

**Bugs:**
AI:
- Jellyfish love to launch themselves out of water
- Many bottom dwelling critters, like sea urchins, nudibranches, cucumbers and starfish love to jump. Maybe make them crawl like spiders on surfaces so they can get up blocks?
- Fish try to swim through anemone's and poison themselves.

Z-fighting found in:
- Anglerfish dorsal, caudal, anal fin & their characteristic, modded fin ray
- Atolla jellyfish on their inside, visible from outside as their outside is a bit seethrough
- Blue spotted stingray has some on its bodies side, especially visible near the eye
- Bull shark top and bottom as teeth overlap
- Cauliflower jellyfish the flower part
- Crab legs
- Discus all fins
- Oarfish front dorsal fin rays at the junctions, why angle them and not make them elongated like the ventral fins?
- Piranha anal fin
- Ratfish first dorsal fin ray (maybe make more of them the same pixel color?)
- Rockfish where back dorsal and caudal fin overlap on one pixel
- Seaangels where their inner body boxes overlap
- Seahorse on all fins
- Stonefish dorsal, anal & caudal fins
- Tetra all fins (also should probably be renamed to "Cardinal tetra", as many other "tetras" exist that look very very different)
- Yellowfin Tuna caudal fin

Others:
- The clownfish seem to just vanish after entering an anemone. I guess they were supposed to work somewhat like beehives? No data is saved tho
- Jellyfish hold their shape when out of water when they should collapse to, well, jelly
- The betta (which I guess is supposed to represent the _betta splendens_) is not its natural fin shape and coloration, but rather achived through centuries of breeding through humans. Plus, pretty much exclusively males have large fins, where as in most betta species all sexes have small fins.
- Discus are also much more brownish/reddish in nature, and pretty much always have a dark, vertical stripe through their eye.
- Dragonfish here have a weird black-yellow texture on their belly?
- Edge of the bullsharks caudal, ventral and the back dorsal fins are just a plain gray texture
- Giant clam accelerates downwards pretty quickly
- Gouramis have more of an upwards facing, inverted ramp looking mouth. Perhaps add a pixel more to the snout at the top?
- On the Lion's Mane Jellyfish the outside (ectoderm) seems to not render the sidetexture of the gastrodermis when looking from the top and bottom, makes the Z-fighting inside (where top and bottom gastrodermis-cube overlap) visible (similar issue with sea nettle, just without the z-fighting)
- Bottom texture of the Nomura jellyfishes ectodermis isn't translucent

I am so excited what this mod will bring in the future!!!

**Comment by BioTechproject27** [comment]
This has been observed in 1.20.1, Version 1.1.0 of the mod

**Comment by MysticKoko** [comment]
Hey, sorry for the late reply, I was busy with university.

First off, thank you for such a detailed issue report, this is actually extremely helpful and I'm glad you like our mod so much
I'm currently going back to all our mobs and working on cleaning up the z-fighting, doing some slight remodels, and giving them all new animations that should make them a lot smoother.

For the AI bugs, we're dedicating our next major update to cleaning up our code and doing maintenance on existing creatures, as well as adding new functions to them where possible, but:
- The "Jumping Jellyfish" bug as we call it in our Discord is going to be fixed in the coming update
- I believe the jumping critters has already been fixed in an update that's been released since you made this issue
- Will look into pathfinding behaviour for the fish and see if we can make them avoid anemones (except Clownfish obviously)

For the "Other" bugs:

- We're aware of the clownfish vanishing, but it was very low on our priority list so we haven't had a chance to look at it yet
- Jellyfish "flop" animations are planned for the coming update, but first we're trying to figure out how to change their hitbox size when they're beached, to avoid having a floppy jellyfish with a 3-block tall hitbox
- Adding fish breeding is something we considered before, but due to time limitations and the fact that aquariums aren't planned for some time, I decided to make bettas (and other aquarium fish) based on their most well-known appearance for now until we move on to adding more aquarium fish with complex mechanics
- Discus texture is inaccurate to real life because of the texture resolution being 16x, so it's hard to include details like eye-stripes on such a small texture, but I'll look into it again just to be sure
- I used [this image](https://animaldiversity.org/collections/contributors/Grzimek_fish/Stomiiformes/Idiacanthus_fasciola/medium.jpg) as my reference when texturing the dragonfish, and this was the best way I could represent the glowing dots on its underside
- All sharks are going to be retextured soon, not sure if it'll be for the upcoming update or later on, but it's planned
- Giant clams have been changed from an entity to a block entity in the latest update, so this problem no longer exists
- Will look into the gourami texture when I reach it in my remodelling/reanimating process I mentioned earlier
- I'll take a look at the nomura and lion's mane jellies, they were slightly rushed so I'm aware they probably have a lot of issues

If you want to talk more about the mod or your ideas for it, you can join our [Discord](https://discord.gg/nwN4vBxg5k) and ping me there anytime, Id love to talk to you more about all this

**Comment by BioTechproject27** [comment]
> Hey, sorry for the late reply, I was busy with university.

No worries, this is a hobby after all :>

> but first we're trying to figure out how to change their hitbox size when they're beached, to avoid having a floppy jellyfish with a 3-block tall hitbox

No idea how coding in java works, but the players hitbox also changes when being squished. Maybe that could be a helpful reference?

> Adding fish breeding is something we considered before

Quite honestly, fish breeding would be pretty low priority on my list, if at all (I mean, fish in vanilla can't be bred either).

> I decided to make bettas (and other aquarium fish) based on their most well-known appearance for now

Yeah, i kinda figured xd Fair enough ig.

> it's hard to include details like eye-stripes on such a small texture

I though of maybe having a grayish/dark orange pixel above and below the eye, but it could look weird.

> I used this image as my reference when texturing the dragonfish, and this was the best way I could represent the glowing dots on its underside

Ahh I see. In that case, maybe having a second layer ever so slightly above it and slightly offset could do the trick? Similar to how some people use the player double skin layer to make stuff like [this](https://www.planetminecraft.com/skin/derp-derp-4021116/)
